# Generated by Django 4.0.4 on 2022-08-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpost',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=5000)),
                ('author', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=120)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
