# Generated by Django 4.0.4 on 2022-08-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_userintracts_userintract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userintract',
            old_name='comments',
            new_name='comment',
        ),
    ]
