# Generated by Django 4.0.4 on 2022-08-11 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpost',
            old_name='srno',
            new_name='sno',
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cpost'),
        ),
    ]
