# Generated by Django 4.0.4 on 2022-08-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_srno_cpost_sno_alter_blogcomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpost',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userintract',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cpost'),
        ),
    ]
